output_sample_rate: 44100
num_channels: 2

sound_card_id: 0
device_id: 0

desired_publishing_rate: 30.0
# num_frames_per_period: 32768
# num_frames_per_period: 16384
# num_frames_per_period: 8192
num_frames_per_period: 4096
# num_output_signals: 28
num_output_signals: 28

published_output_index_range: [4, 12]

# mel_filter_parameter_a: 700.0
# mel_filter_parameter_b: 2595.0
# mel_filter_parameter_a: 200.0
# mel_filter_parameter_b: 22595.0

mel_filter_parameter_a: 200.0
mel_filter_parameter_b: 4096.0
# mel_filter_parameter_b: 16384.0
#mel_filter_parameter_b: 32768.0

apply_hamming_window: false
apply_dct: false

dct_output_scaling:
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
dct_output_offset:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
no_dct_output_scaling:
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
no_dct_output_offset:
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0
  - -0.0

publish_visualization_markers: true
visualization_marker_topic: spectrum_markers_array
visualization_publishing_rate: 20.0
visualization_spectrum_length: 0.5
visualization_spectrum_max_amplitude: 1.0
visualization_spectrum_max_height: 0.25
spectrum_base_frame_pose:
  position:
    x: 0.25
    y: -0.1
    z: 1.8
  orientation:
    w: 1.0
    x: 0.0
    y: 0.0
    z: 0.0