# default_detection_variable_names: [R_LF_th, R_MF_th, R_RF_th, R_LF, R_MF, R_RF, palm_avg, right_finger_avg, middle_finger_avg, left_finger_avg]

default_detection_variable_names: [R_LF_th, R_MF_th, R_RF_th]

# default_detection_variable_names: [audio_0, audio_1, audio_2, audio_3, audio_4, audio_5, audio_6, audio_7, audio_8, audio_9, audio_10, audio_11, audio_12, audio_13, audio_14, audio_15, audio_16, audio_17, audio_18, audio_19, audio_20, audio_21, audio_22, audio_23, audio_24, audio_25, audio_26, audio_27]

#data_sample_filters:
#  -
#    input:
#      - "palm_0"
#      - "palm_1"
#      - "palm_2"
#      - "palm_3"
#      - "palm_4"
#      - "palm_5"
#      - "palm_6"
#      - "palm_7"
#      - "palm_8"
#      - "palm_9"
#      - "palm_10"
#      - "palm_11"
#      - "palm_12"
#      - "palm_13"
#      - "palm_14"
#      - "palm_15"
#      - "palm_16"
#      - "palm_17"
#      - "palm_18"
#      - "palm_19"
#      - "palm_20"
#      - "palm_21"
#      - "palm_22"
#      - "palm_23"
#    output: "palm_avg"
#    method: "avg"
#  -
#    input:
#      - "palm_0"
#      - "palm_1"
#      - "palm_2"
#      - "palm_3"
#      - "palm_4"
#      - "palm_5"
#      - "palm_6"
#      - "palm_7"
#      - "palm_8"
#      - "palm_9"
#      - "palm_10"
#      - "palm_11"
#      - "palm_12"
#      - "palm_13"
#      - "palm_14"
#      - "palm_15"
#      - "palm_16"
#      - "palm_17"
#      - "palm_18"
#      - "palm_19"
#      - "palm_20"
#      - "palm_21"
#      - "palm_22"
#      - "palm_23"
#    output: "palm_max"
#    method: "max"
#  -
#    input:
#      - "right_finger_0"
#      - "right_finger_1"
#      - "right_finger_2"
#      - "right_finger_3"
#      - "right_finger_4"
#      - "right_finger_5"
#      - "right_finger_6"
#      - "right_finger_7"
#      - "right_finger_8"
#      - "right_finger_9"
#      - "right_finger_10"
#      - "right_finger_11"
#      - "right_finger_12"
#      - "right_finger_13"
#      - "right_finger_14"
#      - "right_finger_15"
#      - "right_finger_16"
#      - "right_finger_17"
#      - "right_finger_18"
#      - "right_finger_19"
#      - "right_finger_20"
#      - "right_finger_21"
#      - "right_finger_22"
#      - "right_finger_23"
#    output: "right_finger_avg"
#    method: "avg"
#  -
#    input:
#      - "right_finger_0"
#      - "right_finger_1"
#      - "right_finger_2"
#      - "right_finger_3"
#      - "right_finger_4"
#      - "right_finger_5"
#      - "right_finger_6"
#      - "right_finger_7"
#      - "right_finger_8"
#      - "right_finger_9"
#      - "right_finger_10"
#      - "right_finger_11"
#      - "right_finger_12"
#      - "right_finger_13"
#      - "right_finger_14"
#      - "right_finger_15"
#      - "right_finger_16"
#      - "right_finger_17"
#      - "right_finger_18"
#      - "right_finger_19"
#      - "right_finger_20"
#      - "right_finger_21"
#      - "right_finger_22"
#      - "right_finger_23"
#    output: "right_finger_max"
#    method: "max"
#  -
 #   input:
 #     - "middle_finger_0"
 #     - "middle_finger_1"
 #     - "middle_finger_2"
 #     - "middle_finger_3"
 #     - "middle_finger_4"
 #     - "middle_finger_5"
 #     - "middle_finger_6"
 #     - "middle_finger_7"
 #     - "middle_finger_8"
 #     - "middle_finger_9"
 #     - "middle_finger_10"
 #     - "middle_finger_11"
 #     - "middle_finger_12"
 #     - "middle_finger_13"
 #     - "middle_finger_14"
 #     - "middle_finger_15"
 #     - "middle_finger_16"
 #     - "middle_finger_17"
 #     - "middle_finger_18"
 #     - "middle_finger_19"
 #     - "middle_finger_20"
 #     - "middle_finger_21"
 #     - "middle_finger_22"
 #     - "middle_finger_23"
 #   output: "middle_finger_avg"
 #   method: "avg"
 # -
 #   input:
 #     - "middle_finger_0"
 #     - "middle_finger_1"
 #     - "middle_finger_2"
 #     - "middle_finger_3"
 #     - "middle_finger_4"
 #     - "middle_finger_5"
 #     - "middle_finger_6"
 #     - "middle_finger_7"
 #     - "middle_finger_8"
 #     - "middle_finger_9"
 #     - "middle_finger_10"
 #     - "middle_finger_11"
 #     - "middle_finger_12"
 #     - "middle_finger_13"
 #     - "middle_finger_14"
 #     - "middle_finger_15"
 #     - "middle_finger_16"
 #     - "middle_finger_17"
 #     - "middle_finger_18"
 #     - "middle_finger_19"
 #     - "middle_finger_20"
 #     - "middle_finger_21"
 #     - "middle_finger_22"
 #     - "middle_finger_23"
 #   output: "middle_finger_max"
 #   method: "max"
 # -
 #   input:
 #     - "left_finger_0"
 #     - "left_finger_1"
 #     - "left_finger_2"
 #     - "left_finger_3"
 #     - "left_finger_4"
 #     - "left_finger_5"
 #     - "left_finger_6"
 #     - "left_finger_7"
 #     - "left_finger_8"
 #     - "left_finger_9"
 #     - "left_finger_10"
 #     - "left_finger_11"
 #     - "left_finger_12"
 #     - "left_finger_13"
 #     - "left_finger_14"
 #     - "left_finger_15"
 #     - "left_finger_16"
 #     - "left_finger_17"
 #     - "left_finger_18"
 #     - "left_finger_19"
 #     - "left_finger_20"
 #     - "left_finger_21"
 #     - "left_finger_22"
 #     - "left_finger_23"
 #   output: "left_finger_avg"
 #   method: "avg"
 # -
 #   input:
 #     - "left_finger_0"
 #     - "left_finger_1"
 #     - "left_finger_2"
 #     - "left_finger_3"
 #     - "left_finger_4"
 #     - "left_finger_5"
 #     - "left_finger_6"
 #     - "left_finger_7"
 #     - "left_finger_8"
 #     - "left_finger_9"
 #     - "left_finger_10"
 #     - "left_finger_11"
 #     - "left_finger_12"
 #     - "left_finger_13"
 #     - "left_finger_14"
 #     - "left_finger_15"
 #     - "left_finger_16"
 #     - "left_finger_17"
 #     - "left_finger_18"
 #     - "left_finger_19"
 #     - "left_finger_20"
 #     - "left_finger_21"
 #     - "left_finger_22"
 #     - "left_finger_23"
 #   output: "left_finger_max"
 #   method: "max"
    