# default_detection_variable_names: [R_LF_th, R_MF_th, R_RF_th, R_LF, R_MF, R_RF, palm_avg, right_finger_avg, middle_finger_avg, left_finger_avg]

default_detection_variable_names: [R_LF_th, R_MF_th, R_RF_th]

# default_detection_variable_names: [audio_0, audio_1, audio_2, audio_3, audio_4, audio_5, audio_6, audio_7, audio_8, audio_9, audio_10, audio_11, audio_12, audio_13, audio_14, audio_15, audio_16, audio_17, audio_18, audio_19, audio_20, audio_21, audio_22, audio_23, audio_24, audio_25, audio_26, audio_27]

# data_sample_filters:

# RIGHT HAND

#  -
#    input:
#      - "R_palm_0"
#      - "R_palm_1"
#      - "R_palm_2"
#      - "R_palm_3"
#      - "R_palm_4"
#      - "R_palm_5"
#      - "R_palm_6"
#      - "R_palm_7"
#      - "R_palm_8"
#      - "R_palm_9"
#      - "R_palm_10"
#      - "R_palm_11"
#      - "R_palm_12"
#      - "R_palm_13"
#      - "R_palm_14"
#      - "R_palm_15"
#      - "R_palm_16"
#      - "R_palm_17"
#      - "R_palm_18"
#      - "R_palm_19"
#      - "R_palm_20"
#      - "R_palm_21"
#      - "R_palm_22"
#      - "R_palm_23"
#    output: "R_palm_avg"
#    method: "avg"
#  -
#    input:
#      - "R_palm_0"
#      - "R_palm_1"
#      - "R_palm_2"
#      - "R_palm_3"
#      - "R_palm_4"
#      - "R_palm_5"
#      - "R_palm_6"
#      - "R_palm_7"
#      - "R_palm_8"
#      - "R_palm_9"
#      - "R_palm_10"
#      - "R_palm_11"
#      - "R_palm_12"
#      - "R_palm_13"
#      - "R_palm_14"
#      - "R_palm_15"
#      - "R_palm_16"
#      - "R_palm_17"
#      - "R_palm_18"
#      - "R_palm_19"
#      - "R_palm_20"
#      - "R_palm_21"
#      - "R_palm_22"
#      - "R_palm_23"
#    output: "R_palm_max"
#    method: "max"
#  -
#    input:
#      - "R_right_finger_0"
#      - "R_right_finger_1"
#      - "R_right_finger_2"
#      - "R_right_finger_3"
#      - "R_right_finger_4"
#      - "R_right_finger_5"
#      - "R_right_finger_6"
#      - "R_right_finger_7"
#      - "R_right_finger_8"
#      - "R_right_finger_9"
#      - "R_right_finger_10"
#      - "R_right_finger_11"
#      - "R_right_finger_12"
#      - "R_right_finger_13"
#      - "R_right_finger_14"
#      - "R_right_finger_15"
#      - "R_right_finger_16"
#      - "R_right_finger_17"
#      - "R_right_finger_18"
#      - "R_right_finger_19"
#      - "R_right_finger_20"
#      - "R_right_finger_21"
#      - "R_right_finger_22"
#      - "R_right_finger_23"
#    output: "R_right_finger_avg"
#    method: "avg"
#  -
#    input:
#      - "R_right_finger_0"
#      - "R_right_finger_1"
#      - "R_right_finger_2"
#      - "R_right_finger_3"
#      - "R_right_finger_4"
#      - "R_right_finger_5"
#      - "R_right_finger_6"
#      - "R_right_finger_7"
#      - "R_right_finger_8"
#      - "R_right_finger_9"
#      - "R_right_finger_10"
#      - "R_right_finger_11"
#      - "R_right_finger_12"
#      - "R_right_finger_13"
#      - "R_right_finger_14"
#      - "R_right_finger_15"
#      - "R_right_finger_16"
#      - "R_right_finger_17"
#      - "R_right_finger_18"
#      - "R_right_finger_19"
#      - "R_right_finger_20"
#      - "R_right_finger_21"
#      - "R_right_finger_22"
#      - "R_right_finger_23"
#    output: "R_right_finger_max"
#    method: "max"
#  -
#    input:
#      - "R_middle_finger_0"
#      - "R_middle_finger_1"
#      - "R_middle_finger_2"
#      - "R_middle_finger_3"
#      - "R_middle_finger_4"
#      - "R_middle_finger_5"
#      - "R_middle_finger_6"
#      - "R_middle_finger_7"
#      - "R_middle_finger_8"
#      - "R_middle_finger_9"
#      - "R_middle_finger_10"
#      - "R_middle_finger_11"
#      - "R_middle_finger_12"
#      - "R_middle_finger_13"
#      - "R_middle_finger_14"
#      - "R_middle_finger_15"
#      - "R_middle_finger_16"
#      - "R_middle_finger_17"
#      - "R_middle_finger_18"
#      - "R_middle_finger_19"
#      - "R_middle_finger_20"
#      - "R_middle_finger_21"
#      - "R_middle_finger_22"
#      - "R_middle_finger_23"
#    output: "R_middle_finger_avg"
#    method: "avg"
#  -
#    input:
#      - "R_middle_finger_0"
#      - "R_middle_finger_1"
#      - "R_middle_finger_2"
#      - "R_middle_finger_3"
#      - "R_middle_finger_4"
#      - "R_middle_finger_5"
#      - "R_middle_finger_6"
#      - "R_middle_finger_7"
#      - "R_middle_finger_8"
#      - "R_middle_finger_9"
#      - "R_middle_finger_10"
#      - "R_middle_finger_11"
#      - "R_middle_finger_12"
#      - "R_middle_finger_13"
#      - "R_middle_finger_14"
#      - "R_middle_finger_15"
#      - "R_middle_finger_16"
#      - "R_middle_finger_17"
#      - "R_middle_finger_18"
#      - "R_middle_finger_19"
#      - "R_middle_finger_20"
#      - "R_middle_finger_21"
#      - "R_middle_finger_22"
#      - "R_middle_finger_23"
#    output: "R_middle_finger_max"
#    method: "max"
#  -
#    input:
#      - "R_left_finger_0"
#      - "R_left_finger_1"
#      - "R_left_finger_2"
#      - "R_left_finger_3"
#      - "R_left_finger_4"
#      - "R_left_finger_5"
#      - "R_left_finger_6"
#      - "R_left_finger_7"
#      - "R_left_finger_8"
#      - "R_left_finger_9"
#      - "R_left_finger_10"
#      - "R_left_finger_11"
#      - "R_left_finger_12"
#      - "R_left_finger_13"
#      - "R_left_finger_14"
#      - "R_left_finger_15"
#      - "R_left_finger_16"
#      - "R_left_finger_17"
#      - "R_left_finger_18"
#      - "R_left_finger_19"
#      - "R_left_finger_20"
#      - "R_left_finger_21"
#      - "R_left_finger_22"
#      - "R_left_finger_23"
#    output: "R_left_finger_avg"
#    method: "avg"
#  -
#    input:
#      - "R_left_finger_0"
#      - "R_left_finger_1"
#      - "R_left_finger_2"
#      - "R_left_finger_3"
#      - "R_left_finger_4"
#      - "R_left_finger_5"
#      - "R_left_finger_6"
#      - "R_left_finger_7"
#      - "R_left_finger_8"
#      - "R_left_finger_9"
#      - "R_left_finger_10"
#      - "R_left_finger_11"
#      - "R_left_finger_12"
#      - "R_left_finger_13"
#      - "R_left_finger_14"
#      - "R_left_finger_15"
#      - "R_left_finger_16"
#      - "R_left_finger_17"
#      - "R_left_finger_18"
#      - "R_left_finger_19"
#      - "R_left_finger_20"
#      - "R_left_finger_21"
#      - "R_left_finger_22"
#      - "R_left_finger_23"
#    output: "R_left_finger_max"
#    method: "max"

# LEFT HAND

#  -
#    input:
#      - "L_palm_0"
#      - "L_palm_1"
#      - "L_palm_2"
#      - "L_palm_3"
#      - "L_palm_4"
#      - "L_palm_5"
#      - "L_palm_6"
#      - "L_palm_7"
#      - "L_palm_8"
#      - "L_palm_9"
#      - "L_palm_10"
#      - "L_palm_11"
#      - "L_palm_12"
#      - "L_palm_13"
#      - "L_palm_14"
#      - "L_palm_15"
#      - "L_palm_16"
#      - "L_palm_17"
#      - "L_palm_18"
#      - "L_palm_19"
#      - "L_palm_20"
#      - "L_palm_21"
#      - "L_palm_22"
#      - "L_palm_23"
#    output: "L_palm_avg"
#    method: "avg"
#  -
#    input:
#      - "L_palm_0"
#      - "L_palm_1"
#      - "L_palm_2"
#      - "L_palm_3"
#      - "L_palm_4"
#      - "L_palm_5"
#      - "L_palm_6"
#      - "L_palm_7"
#      - "L_palm_8"
#      - "L_palm_9"
#      - "L_palm_10"
#      - "L_palm_11"
#      - "L_palm_12"
#      - "L_palm_13"
#      - "L_palm_14"
#      - "L_palm_15"
#      - "L_palm_16"
#      - "L_palm_17"
#      - "L_palm_18"
#      - "L_palm_19"
#      - "L_palm_20"
#      - "L_palm_21"
#      - "L_palm_22"
#      - "L_palm_23"
#    output: "L_palm_max"
#    method: "max"
#  -
#    input:
#      - "L_right_finger_0"
#      - "L_right_finger_1"
#      - "L_right_finger_2"
#      - "L_right_finger_3"
#      - "L_right_finger_4"
#      - "L_right_finger_5"
#      - "L_right_finger_6"
#      - "L_right_finger_7"
#      - "L_right_finger_8"
#      - "L_right_finger_9"
#      - "L_right_finger_10"
#      - "L_right_finger_11"
#      - "L_right_finger_12"
#      - "L_right_finger_13"
#      - "L_right_finger_14"
#      - "L_right_finger_15"
#      - "L_right_finger_16"
#      - "L_right_finger_17"
#      - "L_right_finger_18"
#      - "L_right_finger_19"
#      - "L_right_finger_20"
#      - "L_right_finger_21"
#      - "L_right_finger_22"
#      - "L_right_finger_23"
#    output: "L_right_finger_avg"
#    method: "avg"
#  -
#    input:
#      - "L_right_finger_0"
#      - "L_right_finger_1"
#      - "L_right_finger_2"
#      - "L_right_finger_3"
#      - "L_right_finger_4"
#      - "L_right_finger_5"
#      - "L_right_finger_6"
#      - "L_right_finger_7"
#      - "L_right_finger_8"
#      - "L_right_finger_9"
#      - "L_right_finger_10"
#      - "L_right_finger_11"
#      - "L_right_finger_12"
#      - "L_right_finger_13"
#      - "L_right_finger_14"
#      - "L_right_finger_15"
#      - "L_right_finger_16"
#      - "L_right_finger_17"
#      - "L_right_finger_18"
#      - "L_right_finger_19"
#      - "L_right_finger_20"
#      - "L_right_finger_21"
#      - "L_right_finger_22"
#      - "L_right_finger_23"
#    output: "L_right_finger_max"
#    method: "max"
#  -
#    input:
#      - "L_middle_finger_0"
#      - "L_middle_finger_1"
#      - "L_middle_finger_2"
#      - "L_middle_finger_3"
#      - "L_middle_finger_4"
#      - "L_middle_finger_5"
#      - "L_middle_finger_6"
#      - "L_middle_finger_7"
#      - "L_middle_finger_8"
#      - "L_middle_finger_9"
#      - "L_middle_finger_10"
#      - "L_middle_finger_11"
#      - "L_middle_finger_12"
#      - "L_middle_finger_13"
#      - "L_middle_finger_14"
#      - "L_middle_finger_15"
#      - "L_middle_finger_16"
#      - "L_middle_finger_17"
#      - "L_middle_finger_18"
#      - "L_middle_finger_19"
#      - "L_middle_finger_20"
#      - "L_middle_finger_21"
#      - "L_middle_finger_22"
#      - "L_middle_finger_23"
#    output: "L_middle_finger_avg"
#    method: "avg"
#  -
#    input:
#      - "L_middle_finger_0"
#      - "L_middle_finger_1"
#      - "L_middle_finger_2"
#      - "L_middle_finger_3"
#      - "L_middle_finger_4"
#      - "L_middle_finger_5"
#      - "L_middle_finger_6"
#      - "L_middle_finger_7"
#      - "L_middle_finger_8"
#      - "L_middle_finger_9"
#      - "L_middle_finger_10"
#      - "L_middle_finger_11"
#      - "L_middle_finger_12"
#      - "L_middle_finger_13"
#      - "L_middle_finger_14"
#      - "L_middle_finger_15"
#      - "L_middle_finger_16"
#      - "L_middle_finger_17"
#      - "L_middle_finger_18"
#      - "L_middle_finger_19"
#      - "L_middle_finger_20"
#      - "L_middle_finger_21"
#      - "L_middle_finger_22"
#      - "L_middle_finger_23"
#    output: "L_middle_finger_max"
#    method: "max"
#  -
#    input:
#      - "L_left_finger_0"
#      - "L_left_finger_1"
#      - "L_left_finger_2"
#      - "L_left_finger_3"
#      - "L_left_finger_4"
#      - "L_left_finger_5"
#      - "L_left_finger_6"
#      - "L_left_finger_7"
#      - "L_left_finger_8"
#      - "L_left_finger_9"
#      - "L_left_finger_10"
#      - "L_left_finger_11"
#      - "L_left_finger_12"
#      - "L_left_finger_13"
#      - "L_left_finger_14"
#      - "L_left_finger_15"
#      - "L_left_finger_16"
#      - "L_left_finger_17"
#      - "L_left_finger_18"
#      - "L_left_finger_19"
#      - "L_left_finger_20"
#      - "L_left_finger_21"
#      - "L_left_finger_22"
#      - "L_left_finger_23"
#    output: "L_left_finger_avg"
#    method: "avg"
#  -
#    input:
#      - "L_left_finger_0"
#      - "L_left_finger_1"
#      - "L_left_finger_2"
#      - "L_left_finger_3"
#      - "L_left_finger_4"
#      - "L_left_finger_5"
#      - "L_left_finger_6"
#      - "L_left_finger_7"
#      - "L_left_finger_8"
#      - "L_left_finger_9"
#      - "L_left_finger_10"
#      - "L_left_finger_11"
#      - "L_left_finger_12"
#      - "L_left_finger_13"
#      - "L_left_finger_14"
#      - "L_left_finger_15"
#      - "L_left_finger_16"
#      - "L_left_finger_17"
#      - "L_left_finger_18"
#      - "L_left_finger_19"
#      - "L_left_finger_20"
#      - "L_left_finger_21"
#      - "L_left_finger_22"
#      - "L_left_finger_23"
#    output: "L_left_finger_max"
#    method: "max"
    